export interface Parameter {
    unitNumber: string,
    name: string,
    value: string,
    timestamp: Date
}

export interface Unit {
    status: string,
    unitNumber: string,
    customer: string,
    location: string,
    county: string,
    state: string,
    engine: string,
    engineFamily: string,
    engineSerialNum: string,
    afr: string,
    catalyst: string,
    catalystMM: string,
    oemHP: number,
    novaHP: number,
    engineRPM: number,
    frameRPM: number,
    compressorFrame: string,
    compressorFrameFamily: string,
    compressorFrameSN: string,
    stages: string,
    cyclinderSize: string,
    packageMfgDate: Date,
    engineMfgDate: Date,
    zeroHourDate: Date,
    compressorFrameRebuild: Date,
    topEnd: Date,
    oilProvider: string,
    telemetry: string,
    coordinates: string,
    trailerUnit: string,
    unitSetDate: Date,
    billingStartDate: Date,
    billingEndDate: Date,
    lastBillingDate: Date,
    onOffContract: string,
    mtmLastPriceIncrease: string,
    salesperson: string,
    contractTypeTax: string,
    contractTypeOil: string,
    monthlyRate: number,
    recurringDiscount: number,
    salesTax: number,
    adValoremHeit: number,
    netRevenue: number,
    dayRate: string,
    origin: string,
    acqEffDate: Date,
    ownedLeased: string,
    operationalRegion: string,
    financeRegion: string,
    unitProfileUpdateDate: Date,
    financialSku: string,
    oemHPTranche: string,
    bdComments: string,
    opsComments: string,
    setWeek: string,
    releaseWeek: string
}

export interface UnitSatus {
    unitNumber: string,
    status: string,
    statusMessage: string,
    timestamp: Date
}