steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    dir: "${_DIRECTORY}"
    args:
      [
        "build",
        "-t",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/$COMMIT_SHA",
        ".",
      ]
images:
  - "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/$COMMIT_SHA"
options:
  logging: CLOUD_LOGGING_ONLY
